import { Outfit, Young_Serif } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ weight: "400", subsets: ["latin"] });
const youngSerif = Young_Serif({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Recipe Page",
  description: "Generated by kornkawin",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={outfit.className}>
          <div className="flex flex-col h-screen max-h-screen bg-page">
            {/*<Nav/>*/}
            <div className="mx-auto">
              {children}
            </div>
          </div>
        </body>
      </html>
  );
}
