import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  weight: ['400', '700'],
  subsets: ["latin"],
});

export const metadata = {
  title: "QR Card Component",
  description: "Generated by kornkawin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
